"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import AppNav from "../../components/AppNav";

type Mfa = { admin: boolean; configured: boolean; verified: boolean };
export default function AdminPage() {
  const [mfa, setMfa] = useState<Mfa | null>(null); const [secret, setSecret] = useState(""); const [uri, setUri] = useState(""); const [code, setCode] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [stats, setStats] = useState<Record<string, number> | null>(null);
  async function call(path: string, init?: RequestInit) { const res = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await res.json().catch(() => ({})); if (!res.ok) throw new Error(body.message || "Request failed"); return body; }
  async function load() { try { const status = await call("/api/admin/mfa"); setMfa(status); if (status.verified) { const data = await call("/api/admin/overview"); setStats(data.stats); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Administrator access is required."); } }
  useEffect(() => { void load(); }, []);
  async function begin() { setError(""); try { const data = await call("/api/admin/mfa-setup", { method: "POST", body: "{}" }); setSecret(data.secret); setUri(data.otpauthUri); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not begin setup."); } }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await call(mfa?.configured ? "/api/admin/mfa-verify" : "/api/admin/mfa-confirm", { method: "POST", body: JSON.stringify({ code }) }); setNotice("Authenticator verified. Admin access is now active."); setCode(""); setSecret(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Verification failed."); } }
  return <main className="pageShell"><AppNav/><section className="contentWrap"><p className="eyebrow">Restricted control centre</p><h1>Administrator security</h1>{error && <p role="alert">{error}</p>}{notice && <p>{notice}</p>}{mfa && !mfa.configured && <div><p>Set up an authenticator app before you can access administrator controls.</p>{!secret ? <button onClick={begin}>Set up authenticator app</button> : <><p>Add this account in Google Authenticator, Microsoft Authenticator, Authy, or 1Password using the manual setup key:</p><code>{secret}</code><p><small>Account: CarrerFit ({uri ? "TOTP, 6 digits, 30 seconds" : ""})</small></p></>}<MfaForm code={code} setCode={setCode} onSubmit={submit} label="Confirm and enable MFA"/></div>}{mfa?.configured && !mfa.verified && <div><p>Enter the current 6-digit code from your authenticator app to unlock this admin session.</p><MfaForm code={code} setCode={setCode} onSubmit={submit} label="Verify and continue"/></div>}{mfa?.verified && <div><p>Authenticator MFA is verified for this session.</p><div className="gridCards">{Object.entries(stats || {}).map(([key, value]) => <article key={key}><strong>{value}</strong><span>{key.replace(/([A-Z])/g, " $1")}</span></article>)}</div><p><Link href="/job-sources">Manage job sources</Link> · <Link href="/blog-admin">Manage blog posts</Link></p></div>}</section></main>;
}
function MfaForm({ code, setCode, onSubmit, label }: { code: string; setCode: (value: string) => void; onSubmit: (event: FormEvent) => void; label: string }) { return <form onSubmit={onSubmit}><label>Authenticator code <input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} required/></label><button>{label}</button></form>; }
