"use client";

import { FormEvent, useEffect, useState } from "react";
import { BarChart3, BookOpen, Bot, BriefcaseBusiness, CheckCircle2, Clock3, Database, FileText, LayoutDashboard, LogOut, RefreshCw, Search, ShieldCheck, TriangleAlert, Users } from "lucide-react";

type Status = { configured: boolean; authenticated: boolean; sessionHours?: number };
type UserRecord = { id: string; name: string; email: string; verified: boolean; loggedIn: boolean; lastActivityAt: string | null; applications: number; resume: { headline: string; skills: string[] } | null; resumeFile: { filename: string; size: number; uploadedAt: string } | null };
type SourceRecord = { id: string; name: string; url: string; type: string; lastStatus: string; lastError: string | null; lastScrapedAt: string | null; lastImportCount: number; activeJobCount: number };
type PostRecord = { id: string; title: string; category: string; status: string; updatedAt: string };
type BotData = { schedule: string; timezone: string; nextRunAt: string; overview: { stats: { sources: number; activeJobs: number; last24Hours: number; failedSources: number }; sources: SourceRecord[] }; runs: { id: string; trigger: string; status: string; sourceCount: number; refreshed: number; failed: number; startedAt: string; finishedAt: string | null }[] };

const navItems = [
  ["overview", "Dashboard", LayoutDashboard], ["users", "Users", Users], ["resumes", "Resumes", FileText],
  ["bot", "Job bot", Bot], ["jobs", "Jobs & sources", BriefcaseBusiness], ["content", "Blog publishing", BookOpen],
] as const;

export default function AdminPage() {
  const [status, setStatus] = useState<Status | null>(null); const [tab, setTab] = useState("overview"); const [busy, setBusy] = useState(false);
  const [username, setUsername] = useState(""); const [password, setPassword] = useState("");
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [query, setQuery] = useState("");
  const [stats, setStats] = useState<Record<string, number>>({}); const [users, setUsers] = useState<UserRecord[]>([]); const [sources, setSources] = useState<SourceRecord[]>([]); const [posts, setPosts] = useState<PostRecord[]>([]);
  const [botData, setBotData] = useState<BotData | null>(null);
  const [sourceUrl, setSourceUrl] = useState(""); const [sourceName, setSourceName] = useState("");
  const [job, setJob] = useState({ title: "", company: "", location: "", workMode: "Remote", applyUrl: "", skills: "", category: "", level: "", description: "" });
  const [post, setPost] = useState({ title: "", excerpt: "", content: "", category: "Career advice", tags: "", authorName: "CarrerFit Editorial", status: "Draft" });

  async function call(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Request failed"); return body; }
  async function load() { setError(""); try { const result = await call("/api/admin/status"); setStatus(result); if (!result.authenticated) return; const [overview, people, sourceData, blogData, automation] = await Promise.all([call("/api/admin/overview"), call("/api/admin/users"), call("/api/job-sources"), call("/api/blog?admin=1"), call("/api/admin/bot")]); setStats(overview.stats || {}); setUsers(people.users || []); setSources(sourceData.sources || []); setPosts(blogData.posts || []); setBotData(automation); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load the admin console."); } }
  useEffect(() => { void load(); }, []);
  async function perform(action: () => Promise<void>) { setBusy(true); setError(""); setNotice(""); try { await action(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Operation failed."); } finally { setBusy(false); } }
  async function signIn(event: FormEvent) { event.preventDefault(); await perform(async () => { await call("/api/admin/request-access", { method: "POST", body: JSON.stringify({ username, password }) }); setPassword(""); await load(); }); }
  async function logout() { await perform(async () => { await call("/api/admin/logout", { method: "POST", body: "{}" }); setStatus((current) => current ? { ...current, authenticated: false } : current); setUsers([]); setSources([]); setPosts([]); setTab("overview"); }); }
  async function refreshAll() { await perform(async () => { const result = await call("/api/job-sources/scrape-all", { method: "POST", body: "{}" }); setNotice(`${result.refreshed} sources refreshed${result.failed ? `; ${result.failed} failed` : ""}.`); await load(); }); }
  async function runBot() { await perform(async () => { const result = await call("/api/admin/run-bot", { method: "POST", body: "{}" }); setNotice(`Bot completed: ${result.refreshed} refreshed, ${result.failed} failed.`); await load(); }); }
  async function cleanJobs() { await perform(async () => { const result = await call("/api/admin/cleanup-jobs", { method: "POST", body: "{}" }); setNotice(`${result.removed} jobs older than 30 days removed.`); await load(); }); }
  async function addSource(event: FormEvent) { event.preventDefault(); await perform(async () => { const result = await call("/api/job-sources", { method: "POST", body: JSON.stringify({ url: sourceUrl, name: sourceName }) }); setNotice(`${result.imported || 0} jobs imported from the source.`); setSourceUrl(""); setSourceName(""); await load(); }); }
  async function publishJob(event: FormEvent) { event.preventDefault(); await perform(async () => { await call("/api/admin/manual-job", { method: "POST", body: JSON.stringify(job) }); setNotice("Job published to the CarrerFit database."); setJob({ title: "", company: "", location: "", workMode: "Remote", applyUrl: "", skills: "", category: "", level: "", description: "" }); await load(); }); }
  async function publishPost(event: FormEvent) { event.preventDefault(); await perform(async () => { await call("/api/blog", { method: "POST", body: JSON.stringify({ ...post, tags: post.tags.split(",").map((item) => item.trim()).filter(Boolean), featured: false, seoTitle: post.title, seoDescription: post.excerpt, publishedAt: post.status === "Published" ? new Date().toISOString() : null }) }); setNotice(`Blog post saved as ${post.status}.`); setPost({ title: "", excerpt: "", content: "", category: "Career advice", tags: "", authorName: "CarrerFit Editorial", status: "Draft" }); await load(); }); }

  if (!status) return <main className="adminLoading"><RefreshCw className="spin"/><span>Checking secure administrator session…</span></main>;
  if (!status.authenticated) return <main className="adminLoginPage"><section className="adminLoginCard"><span className="adminLoginLogo"><ShieldCheck/></span><p className="adminEyebrow">Private operations</p><h1>CarrerFit Admin</h1><p>Sign in directly with your administrator username and password.</p>{error && <p className="adminMessage error">{error}</p>}{!status.configured ? <p className="adminMessage error">Administrator credentials are not configured.</p> : <form className="adminForm" onSubmit={signIn}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required/></label><button disabled={busy}>{busy ? "Signing in…" : "Open admin dashboard"}</button></form>}<small className="adminLoginHelp">Secure HTTP-only session · 15-minute lock after five failed attempts</small></section></main>;

  const filteredUsers = users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="adminConsole"><aside className="adminSidebar"><div className="adminBrand"><span><BarChart3/></span><div><b>CarrerFit</b><small>ADMIN CONSOLE</small></div></div><nav>{navItems.map(([id, label, Icon]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}><Icon/><span>{label}</span>{id === "users" && <i>{users.length}</i>}</button>)}</nav><div className="adminSidebarFoot"><div><ShieldCheck/><span><b>Secure session</b><small>Expires within {status.sessionHours || 8} hours</small></span></div><button onClick={logout}><LogOut/>Sign out</button></div></aside>
    <section className="adminMain"><header className="adminTopbar"><div className="adminSearch"><Search/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users or records…"/></div><button onClick={() => void load()} disabled={busy}><RefreshCw className={busy ? "spin" : ""}/>Refresh</button><div className="adminAvatar">CF</div></header><div className="adminContent">{error && <p className="adminMessage error">{error}</p>}{notice && <p className="adminMessage">{notice}</p>}
      {tab === "overview" && <Overview stats={stats} users={users}/>} {tab === "bot" && <BotView data={botData} busy={busy} runBot={runBot}/>} {tab === "users" && <UsersView users={filteredUsers}/>} {tab === "resumes" && <ResumesView users={filteredUsers}/>} {tab === "jobs" && <JobsView busy={busy} job={job} setJob={setJob} sourceUrl={sourceUrl} setSourceUrl={setSourceUrl} sourceName={sourceName} setSourceName={setSourceName} sources={sources} addSource={addSource} publishJob={publishJob} refreshAll={refreshAll} cleanJobs={cleanJobs}/>} {tab === "content" && <ContentView busy={busy} post={post} setPost={setPost} posts={posts} publishPost={publishPost}/>} </div></section></main>;
}

function Overview({ stats, users }: { stats: Record<string, number>; users: UserRecord[] }) { const online = users.filter((user) => user.loggedIn).length; const resumes = users.filter((user) => user.resumeFile || user.resume).length; return <><div className="adminPageTitle"><div><p>Dashboard</p><h1>Application overview</h1><span>Live operational data from the CarrerFit production database.</span></div></div><div className="adminMetricGrid"><Metric icon={<Users/>} label="Total users" value={stats.users || 0}/><Metric icon={<ShieldCheck/>} label="Active sessions" value={online}/><Metric icon={<FileText/>} label="Stored resumes" value={resumes}/><Metric icon={<BriefcaseBusiness/>} label="Active jobs" value={stats.activeJobs || 0}/></div><div className="adminDashboardGrid"><section><header><div><b>Recent user activity</b><small>Latest account and resume events</small></div></header>{users.slice(0,6).map((user)=><div className="adminActivity" key={user.id}><span className={user.loggedIn ? "online" : ""}>{initials(user.name)}</span><div><b>{user.name}</b><small>{user.resumeFile ? `Uploaded ${user.resumeFile.filename}` : "Account activity"}</small></div><time>{formatDate(user.lastActivityAt)}</time></div>)}</section><section className="adminHealth"><header><div><b>Platform inventory</b><small>Database-backed content</small></div></header><dl><div><dt>Job sources</dt><dd>{stats.sources || 0}</dd></div><div><dt>Published posts</dt><dd>{stats.publishedPosts || 0}</dd></div><div><dt>Resume coverage</dt><dd>{users.length ? Math.round(resumes / users.length * 100) : 0}%</dd></div></dl></section></div></>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <article><span>{icon}</span><small>{label}</small><strong>{value}</strong></article>; }
function BotView({ data, busy, runBot }: { data: BotData | null; busy: boolean; runBot: () => void }) {
  const latest = data?.runs[0]; const healthy = latest?.status === "Success"; return <><div className="adminPageTitle"><div><p>Automation monitor</p><h1>Job ingestion bot</h1><span>Hourly source synchronization, database imports, and failure visibility.</span></div><div className="adminTitleActions"><button onClick={runBot} disabled={busy}>{busy ? "Bot running…" : "Run bot now"}</button></div></div>
  {!data ? <Empty text="Loading automation status…"/> : <><div className="botStatusHero"><div className={healthy ? "botPulse healthy" : "botPulse warning"}><Bot/></div><div><small>Current status</small><h2>{latest ? latest.status : "Waiting for first recorded run"}</h2><p>{latest ? `Last started ${formatDate(latest.startedAt)}` : "The hourly Hostinger cron is configured and the next run will create history here."}</p></div><div><small>Next scheduled run</small><strong>{formatDate(data.nextRunAt)}</strong><span>{data.schedule} · {data.timezone}</span></div></div>
  <div className="adminMetricGrid botMetrics"><Metric icon={<Database/>} label="Active jobs" value={data.overview.stats.activeJobs}/><Metric icon={<BriefcaseBusiness/>} label="Enabled sources" value={data.overview.stats.sources}/><Metric icon={<CheckCircle2/>} label="Imported in 24h" value={data.overview.stats.last24Hours}/><Metric icon={<TriangleAlert/>} label="Failed sources" value={data.overview.stats.failedSources}/></div>
  <div className="adminBotGrid"><section className="adminPublished"><h2>Source health</h2>{data.overview.sources.map((source)=><article key={source.id}><div>{source.lastStatus === "Success" ? <CheckCircle2/> : <TriangleAlert/>}<span><b>{source.name}</b><small>{source.activeJobCount} active · Last checked {formatDate(source.lastScrapedAt)}</small>{source.lastError && <small className="sourceError">{source.lastError}</small>}</span></div><em className={source.lastStatus === "Success" ? "online" : "offline"}>{source.lastStatus}</em></article>)}</section>
  <section className="adminPublished"><h2>Recent bot runs</h2>{data.runs.length ? data.runs.map((run)=><article key={run.id}><div><Clock3/><span><b>{run.trigger === "cron" ? "Scheduled run" : "Manual run"} · {run.status}</b><small>{run.refreshed}/{run.sourceCount} refreshed · {run.failed} failed</small></span></div><small>{formatDate(run.startedAt)}</small></article>) : <Empty text="No run history yet."/>}</section></div></>}</>;
}
function UsersView({ users }: { users: UserRecord[] }) { return <><div className="adminPageTitle"><div><p>User management</p><h1>Registered users</h1><span>Account status, sessions, applications, and recent activity.</span></div></div><section className="adminTable"><header><span>User</span><span>Status</span><span>Applications</span><span>Last activity</span><span>Resume</span></header>{users.map((user)=><article key={user.id}><div className="adminUser"><i>{initials(user.name)}</i><span><b>{user.name}</b><small>{user.email}</small></span></div><span><em className={user.loggedIn ? "online" : "offline"}>{user.loggedIn ? "Logged in" : user.verified ? "Verified" : "Unverified"}</em></span><span>{user.applications}</span><span>{formatDate(user.lastActivityAt)}</span><span>{user.resumeFile ? <a href={`/api/admin/resume/${user.id}`} target="_blank">Preview</a> : "—"}</span></article>)}</section></>; }
function ResumesView({ users }: { users: UserRecord[] }) { const rows = users.filter((user) => user.resume || user.resumeFile); return <><div className="adminPageTitle"><div><p>Private documents</p><h1>Resume vault</h1><span>Encrypted uploads. Preview access requires this confirmed administrator session.</span></div></div><div className="adminResumeGrid">{rows.map((user)=><article key={user.id}><div><FileText/><span><b>{user.resumeFile?.filename || "Structured resume profile"}</b><small>{user.name} · {user.email}</small></span></div><p>{user.resume?.headline || "Resume analysis stored"}</p><div className="adminSkillRow">{user.resume?.skills.slice(0,5).map((skill)=><span key={skill}>{skill}</span>)}</div>{user.resumeFile ? <a href={`/api/admin/resume/${user.id}`} target="_blank">Open resume preview</a> : <small>Original file predates encrypted file storage.</small>}</article>)}</div>{!rows.length && <Empty text="No users have uploaded a resume yet."/>}</>; }
function JobsView(props: { busy:boolean; job:Record<string,string>; setJob:(value:any)=>void; sourceUrl:string; setSourceUrl:(value:string)=>void; sourceName:string; setSourceName:(value:string)=>void; sources:SourceRecord[]; addSource:(event:FormEvent)=>void; publishJob:(event:FormEvent)=>void; refreshAll:()=>void; cleanJobs:()=>void }) { const field=(key:string,value:string)=>props.setJob({...props.job,[key]:value}); return <><div className="adminPageTitle"><div><p>Jobs database</p><h1>Post and ingest jobs</h1><span>Create roles manually or connect supported public employer job boards.</span></div><div className="adminTitleActions"><button onClick={props.refreshAll}>Refresh sources</button><button onClick={props.cleanJobs}>Clean 30+ day jobs</button></div></div><div className="adminTwoColumns"><form className="adminEditor" onSubmit={props.publishJob}><h2>Post a job manually</h2><div className="adminFormGrid"><label>Job title<input value={props.job.title} onChange={(e)=>field("title",e.target.value)} required/></label><label>Company<input value={props.job.company} onChange={(e)=>field("company",e.target.value)} required/></label><label>Location<input value={props.job.location} onChange={(e)=>field("location",e.target.value)}/></label><label>Work mode<select value={props.job.workMode} onChange={(e)=>field("workMode",e.target.value)}><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label className="wide">Apply URL<input type="url" value={props.job.applyUrl} onChange={(e)=>field("applyUrl",e.target.value)} required/></label><label>Category<input value={props.job.category} onChange={(e)=>field("category",e.target.value)}/></label><label>Level<input value={props.job.level} onChange={(e)=>field("level",e.target.value)}/></label><label className="wide">Skills (comma separated)<input value={props.job.skills} onChange={(e)=>field("skills",e.target.value)}/></label><label className="wide">Description<textarea value={props.job.description} onChange={(e)=>field("description",e.target.value)} required/></label></div><button disabled={props.busy}>Publish job</button></form><form className="adminEditor" onSubmit={props.addSource}><h2>Scrape a supported source</h2><p>Use Lever, Greenhouse, Ashby, or a specific page containing JobPosting structured data. General Google search pages are intentionally rejected.</p><label>Public careers URL<input type="url" value={props.sourceUrl} onChange={(e)=>props.setSourceUrl(e.target.value)} required/></label><label>Company name<input value={props.sourceName} onChange={(e)=>props.setSourceName(e.target.value)}/></label><button disabled={props.busy}>Connect and import</button><div className="adminSourceList">{props.sources.map((source)=><div key={source.id}><span className={source.lastStatus === "Success" ? "success" : ""}/><div><b>{source.name}</b><small>{source.type} · {source.activeJobCount} active jobs</small></div></div>)}</div></form></div></>; }
function ContentView(props: { busy:boolean; post:Record<string,string>; setPost:(value:any)=>void; posts:PostRecord[]; publishPost:(event:FormEvent)=>void }) { const field=(key:string,value:string)=>props.setPost({...props.post,[key]:value}); return <><div className="adminPageTitle"><div><p>Content management</p><h1>Blog publishing</h1><span>Create SEO-ready drafts or publish directly to the CarrerFit career guides.</span></div></div><div className="adminTwoColumns"><form className="adminEditor" onSubmit={props.publishPost}><h2>Create blog post</h2><label>Title<input value={props.post.title} onChange={(e)=>field("title",e.target.value)} required/></label><label>Excerpt<textarea value={props.post.excerpt} onChange={(e)=>field("excerpt",e.target.value)} required/></label><label>Article content (Markdown)<textarea className="tall" value={props.post.content} onChange={(e)=>field("content",e.target.value)} required/></label><div className="adminFormGrid"><label>Category<input value={props.post.category} onChange={(e)=>field("category",e.target.value)}/></label><label>Tags<input value={props.post.tags} onChange={(e)=>field("tags",e.target.value)} placeholder="resume, interview"/></label><label>Author<input value={props.post.authorName} onChange={(e)=>field("authorName",e.target.value)}/></label><label>Status<select value={props.post.status} onChange={(e)=>field("status",e.target.value)}><option>Draft</option><option>Published</option></select></label></div><button disabled={props.busy}>Save blog post</button></form><section className="adminPublished"><h2>All posts</h2>{props.posts.map((post)=><article key={post.id}><div><BookOpen/><span><b>{post.title}</b><small>{post.category} · Updated {formatDate(post.updatedAt)}</small></span></div><em className={post.status === "Published" ? "online" : "offline"}>{post.status}</em></article>)}</section></div></>; }
function Empty({ text }: { text:string }) { return <div className="adminEmpty"><Database/><p>{text}</p></div>; }
function initials(value:string){return value.split(/\s+/).map((part)=>part[0]).join("").slice(0,2).toUpperCase();}
function formatDate(value:string|null){return value?new Date(value).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"}):"Never";}
