import type { AtsAnalysis, ResumeDocument } from "../lib/types.js";

const ACTION_VERBS = ["achieved", "built", "created", "delivered", "designed", "developed", "drove", "improved", "increased", "launched", "led", "managed", "optimized", "reduced", "saved", "scaled", "streamlined", "implemented", "automated", "generated"];

export function analyzeAts(text: string, document: ResumeDocument): AtsAnalysis {
  const normalized = text.replace(/\r/g, "").trim();
  const lines = normalized.split("\n").map((line) => line.trim()).filter(Boolean);
  const wordCount = document.wordCount || normalized.split(/\s+/).filter(Boolean).length;
  const quantified = lines.filter((line) => /(?:\b\d+(?:\.\d+)?%|\b(?:₹|\$|£|€)\s?[\d,.]+|\b\d+\+?\s+(?:users|clients|projects|people|hours|days|weeks|months|years|members|customers)\b)/i.test(line)).length;
  const actionBullets = lines.filter((line) => ACTION_VERBS.some((verb) => new RegExp(`^(?:[•●▪◦*\\-–—]\\s*)?${verb}\\b`, "i").test(line))).length;
  const has = (pattern: RegExp) => pattern.test(normalized);
  const hasSection = (...names: string[]) => names.some((name) => document.sectionsDetected.some((section) => section.toLowerCase().includes(name)) || new RegExp(`(?:^|\\n)\\s*${name}\\s*(?:\\n|:)`, "i").test(normalized));
  const uniqueKeywords = new Set([...document.keywords, ...document.skills.map((skill) => skill.name)].map((item) => item.trim().toLowerCase()).filter(Boolean));
  const categories: AtsAnalysis["categories"] = [
    { name: "Contact", weight: 15, score: points([[Boolean(document.identity.email || has(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i)), 35], [Boolean(document.identity.phone), 30], [Boolean(document.identity.location), 15], [document.identity.links.length > 0, 20]]), checks: [check("Email", Boolean(document.identity.email), "Include one professional email in plain text."), check("Phone", Boolean(document.identity.phone), "Include a reachable phone number with country code."), check("Professional link", document.identity.links.length > 0, "Add LinkedIn, GitHub, or a portfolio URL.")] },
    { name: "Structure", weight: 20, score: points([[hasSection("experience", "employment", "work history"), 35], [hasSection("skills", "technical skills", "core competencies"), 25], [hasSection("education", "academic"), 25], [hasSection("summary", "profile", "objective"), 15]]), checks: [check("Experience section", hasSection("experience", "employment", "work history"), "Use a clearly labelled Experience section."), check("Skills section", hasSection("skills", "technical skills", "core competencies"), "Use a dedicated Skills section."), check("Education section", hasSection("education", "academic"), "Use a clearly labelled Education section.")] },
    { name: "Content", weight: 30, score: points([[quantified >= 3, 35], [quantified >= 1, 15], [actionBullets >= 4, 30], [actionBullets >= 1, 15], [document.experience.length > 0, 20]]), checks: [check("Measured impact", quantified >= 3, `${quantified} quantified achievements detected; aim for at least 3.`), check("Action-led bullets", actionBullets >= 4, `${actionBullets} action-led bullets detected; lead bullets with outcomes.`), check("Experience evidence", document.experience.length > 0, "Add roles, dates, responsibilities, and outcomes.")] },
    { name: "Keywords", weight: 20, score: points([[uniqueKeywords.size >= 12, 45], [uniqueKeywords.size >= 6, 25], [document.skills.filter((skill) => skill.evidence).length >= 5, 35], [document.projects.length + document.certifications.length > 0, 20]]), checks: [check("Searchable vocabulary", uniqueKeywords.size >= 12, `${uniqueKeywords.size} unique skills and keywords detected.`), check("Evidence-backed skills", document.skills.filter((skill) => skill.evidence).length >= 5, "Connect important skills to work or project evidence."), check("Projects or credentials", document.projects.length + document.certifications.length > 0, "Add relevant projects or certifications when applicable.")] },
    { name: "Readability", weight: 15, score: points([[wordCount >= 300 && wordCount <= 1_100, 45], [lines.length >= 18, 20], [(normalized.match(/[�□■]/g)?.length || 0) < 3, 20], [document.extractionConfidence >= .7, 15]]), checks: [check("Useful length", wordCount >= 300 && wordCount <= 1_100, `${wordCount} words detected; 300–1,100 is a practical parsing range for most resumes.`), check("Text extraction", document.extractionConfidence >= .7, `${Math.round(document.extractionConfidence * 100)}% extraction confidence.`), check("Clean characters", (normalized.match(/[�□■]/g)?.length || 0) < 3, "Export a clean text-based PDF or DOCX if symbols appear corrupted.")] },
  ];
  const score = Math.round(categories.reduce((sum, category) => sum + category.score * category.weight / 100, 0));
  const failed = categories.flatMap((category) => category.checks.filter((item) => !item.passed).map((item) => item.detail));
  return { score, label: score >= 85 ? "Strong" : score >= 70 ? "ATS ready" : score >= 50 ? "Developing" : "Needs work", disclaimer: "Compatibility estimate based on extracted text and common parsing practices; it cannot guarantee results in every employer ATS.", categories, strengths: categories.flatMap((category) => category.checks.filter((item) => item.passed).map((item) => item.label)).slice(0, 5), priorityFixes: [...new Set(failed)].slice(0, 6), metrics: { words: wordCount, sections: document.sectionsDetected.length, skills: document.skills.length, quantifiedAchievements: quantified, actionVerbBullets: actionBullets } };
}

function points(items: [boolean, number][]) { return Math.min(100, items.reduce((total, [passed, value]) => total + (passed ? value : 0), 0)); }
function check(label: string, passed: boolean, detail: string) { return { label, passed, detail }; }
